# Generated by Django 4.2.24 on 2025-09-10 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EffectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('user_description', models.TextField()),
                ('hidden_prompt', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='effect_thumbnails/')),
                ('strength', models.FloatField(default=0.7)),
                ('preserve_faces', models.BooleanField(default=True)),
                ('max_resolution', models.CharField(default='2048x2048', max_length=20)),
                ('output_format', models.CharField(default='jpeg', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects.effectcategory')),
            ],
        ),
    ]
