# Generated by Django 4.2.24 on 2025-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
    ]
